Display more elaborate message in the error for comparison of subjects present in participants.tsv and the ones present in the BIDS layout
aces/Loris-MRI pull request #617
Opened 2021-05-11 15:34 UTC by cmadjar

This PR improves a little the logs of the error when doing comparison between the list of subjects present in participants.tsv and the list of subjects grepped by the BIDS reader.

2021-05-20 19:28 UTC, cmadjar commented
@laemtl If you have some time to review this one. Should be a relatively quick one.

2021-07-05 15:08 UTC, vietdhoang requested changes
I added some suggestions to account for the fact that `print()` automatically adds a newline at the end.

I also added a suggestion for how a multi-line string can be formatted. This suggestion can be ignored if the current format is preferred or is the standard at LORIS

2021-07-05 15:08 UTC, vietdhoang commented on python/lib/bidsreader.py
>                             "participants.tsv and raw data found in the BIDS " \
```suggestion
        mismatch_message = ("\nERROR: Participant ID mismatch between "
                            "participants.tsv and raw data found in the BIDS "
```

2021-07-05 15:08 UTC, vietdhoang commented on python/lib/bidsreader.py
> +                           "directory\n"
```suggestion
                            "directory")
```

2021-07-06 13:34 UTC, cmadjar commented
@vietdhoang thank you! I committed the changes. :)

2021-07-15 21:18 UTC, merged