Participants.tsv: Use project and site name instead of alias
aces/Loris-MRI pull request #647
Opened 2021-07-29 20:02 UTC by laemtl

Adapt the logic from #558 to use project and site Names instead of Alias.

Motivations: 
  - readibility
  - uniformity (subproject's value is subproject's title)
  - follow API's logic where project and site Names are used

Note: In candidate.py, the if self.site case was deleted. To my understanding, it wil lbe populated after the first iter with the first participant's site, and assume that all subsequent participants are from the same site, which is not necessary the case.

2021-08-04 15:03 UTC, cmadjar requested changes
@laemtl One tiny change on the log text to reflect that we are showing CenterID and ProjectID values instead of site and project name in the logs

2021-08-04 15:03 UTC, cmadjar commented on python/lib/candidate.py
>                    "Project = " + str(self.project_id))
```suggestion
                  "CenterID = "    + str(self.center_id)  + ", " + \
                  "ProjectID = " + str(self.project_id))
```

2021-08-04 21:07 UTC, laemtl commented
@cmadjar Done!

2021-08-05 14:23 UTC, cmadjar approved these changes
Code looks good and tested locally and it works great! 👍

2021-08-05 14:23 UTC, merged