Add bids_export_files table to the delete script
aces/Loris-MRI pull request #736
Opened 2021-12-02 15:57 UTC by cmadjar

This allows the deletion of files derived from a `FileID` in the `bids_export_files` when there are BIDS files present for the `FileID` to be deleted.

Resolves #723

2021-12-02 18:06 UTC, zaliqarosli requested changes
there are entries in the bids_export_files table that are associated with a specific upload ID but in the table, the rows are associated with the upload's session ID and not the File IDs. the files are the .json and .tsv files:

```
mysql> select * from bids_export_files where FileID IN (SELECT FileID from files where SessionID='22') OR SessionID='22';
+--------------------+-------------------------------+--------+-----------+------------------------------+----------------+----------+--------------------------------------------------------------------------------------------------------+
| BIDSExportedFileID | BIDSExportFileLevelCategoryID | FileID | SessionID | BIDSNonImagingFileCategoryID | BIDSCategoryID | FileType | FilePath                                                                                               |
+--------------------+-------------------------------+--------+-----------+------------------------------+----------------+----------+--------------------------------------------------------------------------------------------------------+
|                  6 |                             2 |    244 |      NULL |                         NULL |           NULL | nii      | BIDS_export/BIDS_LORIS24_test/sub-300022/ses-V1/anat/sub-300022_ses-V1_acq-bla_run-1_inv-20_T1w.nii.gz |
|                  7 |                             2 |    244 |      NULL |                         NULL |              1 | json     | BIDS_export/BIDS_LORIS24_test/sub-300022/ses-V1/anat/sub-300022_ses-V1_acq-bla_run-1_inv-20_T1w.json   |
|                  8 |                             3 |   NULL |        22 |                            5 |           NULL | tsv      | BIDS_export/BIDS_LORIS24_test/sub-300022/ses-V1/sub-300022_ses-V1_scans.tsv                            |
|                  9 |                             3 |   NULL |        22 |                            5 |           NULL | json     | BIDS_export/BIDS_LORIS24_test/sub-300022/ses-V1/sub-300022_ses-V1_scans.json                           |
|                 10 |                             2 |    245 |      NULL |                         NULL |           NULL | nii      | BIDS_export/BIDS_LORIS24_test/sub-300022/ses-V1/anat/sub-300022_ses-V1_run-1_T2w.nii.gz                |
|                 11 |                             2 |    245 |      NULL |                         NULL |              1 | json     | BIDS_export/BIDS_LORIS24_test/sub-300022/ses-V1/anat/sub-300022_ses-V1_run-1_T2w.json                  |
+--------------------+-------------------------------+--------+-----------+------------------------------+----------------+----------+--------------------------------------------------------------------------------------------------------+
6 rows in set (0.01 sec)
```

these files/rows don't seem to be targeted in the backup files

2021-12-08 18:05 UTC, cmadjar commented
@zaliqarosli thank you for pointing that out! Should be fixed now :-).

2021-12-08 21:04 UTC, zaliqarosli approved these changes

2021-12-09 14:59 UTC, nicolasbrossard requested changes
Didn't test this but code looks good. You forgot to regenerate the associated `.md` file though.  :)

2021-12-09 15:30 UTC, merged