dcm2bids insertion pipeline
aces/Loris-MRI pull request #752
Opened 2021-12-21 19:13 UTC by cmadjar

2022-01-28 15:02 UTC, cmadjar commented
Tests performed:
- [x] on raisin bread dataset
- [x] on all IBIS protocols
- [x] protocol identification 
- [x] protocol checks (warning and exclude)
- [x] pic creation
- [x] MRI violations
- [x] bids_import.py pipeline on datasets with EEG, MRI and annotations 
- [ ] full pipeline from DICOM files

2022-02-01 17:11 UTC, christinerogers requested changes
Hi @cmadjar, 
Awesome work.  
I've suggested lots of little simplifying edits for easier reading, let me know what you think - I tried to ensure the precise meaning was retained. 
Thanks,
Christine

2022-02-01 17:11 UTC, christinerogers commented on docs/04-Scripts.md
> +the execution of the pipeline are shown below.
```suggestion
the execution of the pipeline is shown below. 
```
(because illustration is singular)

2022-02-01 17:11 UTC, christinerogers commented on docs/04-Scripts.md
> +The DICOM insertion part is identical to the DICOM to MINC pipeline flow. After the
```suggestion
The DICOM insertion steps are quite similar to the DICOM to MINC pipeline flow. After the 
```

2022-02-01 17:11 UTC, christinerogers commented on docs/04-Scripts.md
> +NIfTI volumes with their JSON side file can be **force-loaded** into LORIS by running:
```suggestion
NIfTI volumes with their JSON sidecar files can be **force-loaded** into LORIS by running:
```

2022-02-01 17:11 UTC, christinerogers commented on docs/05-PipelineLaunchOptions.md
> +## 5.2 - Pipeline Launch for BIDS datasets directly (no DICOM files available)
```suggestion
## 5.2 - Pipeline Launch for BIDS datasets directly (if no DICOM files available)
```

2022-02-02 16:34 UTC, cmadjar commented on docs/02-Install.md
> +that should be used to determine the name of the NIfTI and JSON files. That table is linked
I replaced with "labelling convention". Is that better?

2022-02-02 16:57 UTC, cmadjar reviewed
Thank you @christinerogers for the review and suggestions! Much better now. 

See attached comments for some responses.

2022-02-02 16:57 UTC, cmadjar commented on docs/02-Install.md
> +`task-rest`, `dir-AP`, `dir-PA`, `acq-B0_dir-AP`)
ok. Added the link to the BIDS spec to your descriptoin.

2022-02-02 16:57 UTC, cmadjar commented on docs/02-Install.md
> +after having run the mnc2bids conversion script (`tools/minc_to_bids_converter.pl`)
ok. Just kept `by` here as I don't understand the `(or downstream from)`. Hope that works

2022-02-02 16:57 UTC, cmadjar commented on docs/02-Install.md
> +    when running the Python insertion scripts (typically `database_config.py`)
I left it because this is how the whole section is formatted.

2022-02-02 16:57 UTC, cmadjar commented on docs/02-Install.md
> +whether the pipeline should produce MINC files (`dcm2mnc`) or BIDS compatible files (`dcm2niix`)
nice! Much better :)

2022-02-02 16:57 UTC, cmadjar commented on docs/03-TechnicalInfrastructure.md
> +  converter from the MINC tools for MINC files and `dcm2niix` for BIDS files),
so much better! I was not happy with what I wrote but could not do better...

2022-02-02 16:57 UTC, cmadjar commented on docs/04-Scripts.md
> +the execution of the pipeline are shown below.
ooops, haha

2022-02-03 05:38 UTC, christinerogers commented
looks good to me --though one more fix : this comment https://github.com/aces/Loris-MRI/pull/752#discussion_r797816367 refers to some text that says `key and expected outcomes` which sounds a little weird. 
I'd suggest editing to just say `outcomes`.  or else try `...illustration summarizing the main outcomes`

2022-02-03 05:39 UTC, christinerogers commented on docs/02-Install.md
> +that should be used to determine the name of the NIfTI and JSON files. That table is linked
sure labelling convention is good

2022-02-03 05:44 UTC, christinerogers approved these changes

2022-02-03 19:18 UTC, merged