[EEG-BIDS] Add support for events.json file & HED Tags
aces/Loris-MRI pull request #769
Opened 2022-03-09 18:16 UTC by jesscall

### Add support to bids_import for `*events.json` file & HED Tags
#### Scope
This PR refactors how the bids_import handles event files. It adds support for an event.json file in which HED tags can be stored. The PR edits the fetching and inserting of event files and adds an archiving feature similar to the annotation files. 

#### Information
Please reference this documentation for more info on [HED Tags in BIDS](https://bids-specification.readthedocs.io/en/latest/99-appendices/03-hed.html)

#### Testing
1. The SQL patches from https://github.com/aces/Loris/pull/8036 should be sourced before attempting to test these changes.
2. Place the sample [`*events.json` file](https://github.com/aces/Loris-MRI/files/8209484/task-faceO_events.json.zip) at the root of the RB BIDS directory. 
3. Attempt to test the changes in this PR
4. Try putting the `*events.json` file in a subject directory (and renaming) and make sure the import still runs as expected.

2022-03-15 16:43 UTC, jesscall commented
@cmadjar I made the database_lib additions - I haven't had a chance to re-test the import however. I'll try to get to this by end of week

2022-03-15 16:45 UTC, jesscall commented on python/lib/database_lib/physiologicaleventparameter.py
> +                    'Units', 'isCategorical', 'HED'),
@cmadjar any idea how much of an indent is acceptable here ? 😭

2022-05-13 14:16 UTC, jesscall commented
**Bug:** 
- The events.json is being stored at the individual candidate level. Should be stored only once at the BIDS root level... @cmadjar I haven't had the chance to debug this yet. Any ideas off the top of your head how I can achieve this since you are more familiar with the code? 

Also to note:
There will be some more changes coming to this PR to account for HED tag assembly.

2022-06-02 18:52 UTC, jesscall commented
This PR now supports assembly of events' HED tags using the [HEDtools web service](https://hed-examples.readthedocs.io/en/latest/HedToolsOnline.html#hed-restful-services).

2022-06-02 19:46 UTC, jesscall commented on python/lib/physiological.py
> +                print(hedDict[index])
```suggestion
```

2022-06-14 15:22 UTC, jesscall commented on python/lib/physiological.py
> +                        else None
```suggestion
                    levelDescription = event_metadata[parameter]['Levels'][level]
                    levelHED = event_metadata[parameter]['HED'][level] \
                        if level in event_metadata[parameter]['HED'] \
                        else None
```

2022-06-14 15:25 UTC, jesscall commented
@cmadjar I believe this commit af956f7d8704d8c3c153645a1b3476c7556eb65f will address the issue with `physiological_event_parameter_category_level` saving

2022-06-14 15:30 UTC, jesscall commented on python/lib/eeg.py
> +                        print(f"WARNING: no events metadata files (event.json) associated with physiological file ID {physiological_file_id}")
```suggestion
                        message = '\nWARNING: no events metadata files (event.json) associated' + /
                                  'with physiological file ID ' + physiological_file_id
                        print(message)
```

2022-06-14 15:37 UTC, jesscall commented on python/lib/eeg.py
> +                        message = '\nWARNING: no events metadata files (event.json) associated' + /
```suggestion
                        message = '\nWARNING: no events metadata files (event.json) associated' +/
```

2022-06-17 19:02 UTC, cmadjar requested changes
@jesscall see replies to your comments.

Also, once the LORIS side has been changed to link the file types to `ImagingFileTypes`, a little reminder to modify the code here to reflect on the DB structure

2022-06-17 19:02 UTC, cmadjar commented on python/lib/database_lib/physiologicaleventfile.py
> +    def grep_event_file_id_from_event_path(self, event_file_path):
ok. But what happens in the example above where the same TSV file links to two different `PhysiologicalFileID`? Would it just return the first `PhysiologicalFileID` encountered? If so, sounds like a possible major bug, no?

2022-06-17 19:02 UTC, cmadjar commented on python/lib/eeg.py
> +                        message = '\nWARNING: no events metadata files (event.json) associated' +/
```suggestion
                        message = '\nWARNING: no events metadata files (event.json) associated' +
```

I think the above is what the line should be. There is an extra `/` that should not be there

2022-06-20 14:51 UTC, jesscall commented on python/lib/database_lib/physiologicaleventfile.py
> +    def grep_event_file_id_from_event_path(self, event_file_path):
Where do you see the case where two tsv point to the same physioFile?

2022-06-20 17:40 UTC, cmadjar commented on python/lib/database_lib/physiologicaleventfile.py
> +    def grep_event_file_id_from_event_path(self, event_file_path):
when the event.tsv file is identical for all EEG files and therefore put directly under root. I believe this is possible in BIDS.

2022-06-20 17:41 UTC, cmadjar commented on python/lib/eeg.py
>                                    'with physiological file ID ' + physiological_file_id
```suggestion
                        message = '\nWARNING: no events metadata files (event.json) associated' \
                                  'with physiological file ID ' + physiological_file_id
```

Try that instead maybe?

2022-06-20 17:46 UTC, jesscall commented on python/lib/database_lib/physiologicaleventfile.py
> +    def grep_event_file_id_from_event_path(self, event_file_path):
The event.json file can be shared by all subjects. I don't think the events.tsv can ? This means that ALL recordings have the same events/ stimulus? Seems unlikely, but I could be wrong. Do you have an example of this in the spec somewhere?

2022-06-21 20:18 UTC, cmadjar commented on python/lib/database_lib/physiologicaleventfile.py
> +    def grep_event_file_id_from_event_path(self, event_file_path):
From the BIDS specs: https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/05-task-events.html

```
It is also possible to have a single events.tsv file describing events for all participants and runs (see [Inheritance Principle](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#the-inheritance-principle)).
```

2022-06-22 14:18 UTC, jesscall commented on python/lib/database_lib/physiologicaleventfile.py
> +    def grep_event_file_id_from_event_path(self, event_file_path):
Fixed by passing in physioFileID as a param in the query

2022-06-22 14:19 UTC, jesscall commented on python/lib/database_lib/physiologicaleventfile.py
> +                    "WHERE FilePath = %s
```suggestion
                    "WHERE FilePath = %s "
```

2022-06-22 14:21 UTC, jesscall commented on python/lib/database_lib/physiologicaleventfile.py
> +                    AND PhysiologicalFileID = %s",
```suggestion
                    "AND PhysiologicalFileID = %s",
```

2022-06-28 18:38 UTC, merged