Refactor remaining array configs to use ConfigOB instead of the DBI library
aces/Loris-MRI pull request #770
Opened 2022-03-16 21:52 UTC by cmadjar

This PR finishes the refactoring of the database config queries to use ConfigOB instead of the DBI library directly.

This resolves #465

2022-03-19 13:56 UTC, nicolasbrossard reviewed
Haven't tested this yet, just reviewed it. Full Moose compliance for the Config. Moo Moo !!!!

2022-03-19 13:56 UTC, nicolasbrossard commented on tools/delete_imaging_upload.pl
> +        return @scanTypes ? (map { $_ => 1 } @scanTypes) : ();
This would be sufficient
```
return (map { $_ => 1 } @scanTypes);
```
(i.e not need for the ternary operator)

2022-03-19 13:56 UTC, nicolasbrossard commented on docs/scripts_md/MRIProcessingUtility.md
> +- Around line 1883:
This has nothing to do with your PR but it seems like there is some invalid Perl doc in `uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm`. Might be a good time to clean it up.  :)

2022-06-03 13:30 UTC, cmadjar commented
@nicolasbrossard ready for another review. Thank you!

2022-06-17 15:57 UTC, nicolasbrossard requested changes

2022-06-17 15:57 UTC, nicolasbrossard commented on tools/run_defacing_script.pl
> +    my ($session_id_arr, @modalities_to_deface_arr) = @_;
I would rename these variables:
- `$session_id_arr` should be `$session_ids_ref` (it's a reference)
- `@modalities_to_deface_arr` should be `@modalities_to_deface`

2022-06-17 15:57 UTC, nicolasbrossard commented on uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
> +=head3 dicom_to_minc($study_dir, $converter, $get_dicom_info, @exclude, $mail_user, $upload_id)
`@exclude` has to be the last parameter for this to work.

2022-06-17 20:26 UTC, nicolasbrossard requested changes

2022-06-17 20:26 UTC, nicolasbrossard commented on tools/run_defacing_script.pl
> +=head3 grep_FileIDs_to_deface($session_id_arr, @modalities_to_deface_arr)
Plz change param names.  :) Don't forget the `.md` file too!

2022-06-17 20:26 UTC, nicolasbrossard commented on tools/run_defacing_script.pl
> +  - @modalities_to_deface_arr: array of Scan_type to use when grepping FileIDs
Incorrect param names

2022-06-17 20:26 UTC, nicolasbrossard commented on docs/scripts_md/run_defacing_script.md
> +### grep\_FileIDs\_to\_deface($session\_id\_arr, @modalities\_to\_deface\_arr)
This `.md` file needs to be regenerated

2022-06-17 20:56 UTC, cmadjar commented
@nicolasbrossard good catch! Should be fixed in the last commit

2022-09-01 14:44 UTC, nicolasbrossard requested changes

2022-09-01 14:44 UTC, nicolasbrossard commented on uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm
> +RETURN: an array (possibly empty) of the acknowledgment text to use for a BIDS dataset
I don't think this method returns an array but a string. Also, when you do not define an acknowledgment text, this method returns `undef` (not the empty string `''`). Is this the intended behavior?

2022-09-01 14:44 UTC, nicolasbrossard commented on uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm
> +RETURN: an array (possibly empty) of the README text to use for a BIDS dataset
Same comment as for the acknowledgment text.

2023-02-17 16:09 UTC, merged