Keep additional events - rename Task to Property
aces/Loris-MRI pull request #900
Opened 2023-03-08 17:19 UTC by regisoc

Change the `TaskName` and `TaskValue` to `PropertyName` and `PropertyValue` for additional event integration.

2023-03-08 17:41 UTC, jeffersoncasimir approved these changes

2023-03-08 20:45 UTC, christinerogers requested changes
see my comments on #8432 as well in Loris repo

2023-03-08 20:45 UTC, christinerogers commented on python/lib/physiological.py
>                      'PhysiologicalTaskEventID',
Could `PhysiologicalTaskEventID` be changed too?

2023-03-09 14:47 UTC, cmadjar commented
Blocked by https://github.com/aces/Loris/pull/8432 which need to be merged at the same time as this PR on main.

2023-03-09 14:48 UTC, cmadjar requested changes
@regisoc isn't this supposed to go on main since the SQL changes go to main on the LORIS side?

2023-03-09 14:53 UTC, regisoc commented
Yes, but we agreed on the `try/catch` bloc in `LORIS-MRI` that will make the routing depending on the code version in `LORIS`: `24.1` does not have the SQL change on LORIS, but `main` has. I was told to push this on `24.1` but I can change it if that is not convenient anymore.

2023-03-09 15:00 UTC, cmadjar commented
@regisoc right, so if SQL is the main version, the code changed here will be run, otherwise it will still run the old code. Sounds good then

2023-03-09 15:06 UTC, cmadjar commented
@christinerogers is that OK with you to get merged? I see you requested changes but the sentence says `looks ok to me...`. If all good, could you please edit your review and approve the PR? Thanks!

2023-03-10 16:33 UTC, christinerogers approved these changes

2023-03-10 16:33 UTC, merged